name: PushToEsoUI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true
        default: '3.0.1'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Pushing
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'AltBossBar'

      - name: Zip release
        run: 7z a AltBossBar.zip * -xr!*.git*

      - name: Push to EsoUI
        id: push
        uses: M0RGaming/Push-To-EsoUI@main
        with:
          EsoUIToken: ${{secrets.ESOUI_API_TOKEN}}
          EsoUIID: 3820
          path: './AltBossBar/'
          version: ${{github.event.inputs.version}}
          artifact: 'AltBossBar.zip'